name: Actualizador de Payloads

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  generar-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Descargar mi repositorio
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar el script buscador
        run: python actualizador.py

      - name: Guardar los cambios (Commit)
        run: |
          git config --global user.name "Bot Payload"
          git config --global user.email "bot@github.com"
          git add repo.json
          
          if git status --porcelain | grep -q "repo.json"; then
            git commit -m "Actualizados payloads"
            git push
          else
            echo "No hay actualizaciones nuevas, no hace falta guardar nada."
          fi
